site_name: Charizone
theme:
  name: null
  custom_dir: cz_theme
plugins:
  cz_blog:
    footernav:
      - Read our FAQs: 'about.md'
      - About Charizone: 'about.md'
      - Our Methodology: 'our-methodology.md'
    articles_folder: articles
    privacy: 'privacy.md'
nav:
  - Charizone: 'index.md'
  - About: 'about.md'
  - Our Methodology: 'our-methodology.md'
  - Articles and Insights: 'articles.md'
watch:
  - cz_theme
  - cz_blog
extra:
  twitter: https://twitter.com/charizone
  linkedin: https://linkedin.com/charizone