site_name: Charizone
site_url: !ENV DEPLOY_PRIME_URL
theme:
  name: null
  custom_dir: cz_theme
plugins:
  cz_blog:
    footernav:
      - About: "about.md"
      - Resources: "articles.md"
      - Contact: "contact.md"
    articles_folder: articles
    privacy: "privacy.md"
    terms: "terms-and-conditions.md"
  gen-files:
    scripts:
      - add_charities.py
nav:
  - About: "about.md"
  - Our approach: "approach.md"
  - Resources: "articles.md"
  - Contact: "contact.md"
watch:
  - cz_theme
  - cz_blog
  - add_charities.py
extra:
  appointment_booker: https://calendar.google.com/calendar/appointments/schedules/AcZssZ1Rif_CiZSLSMJzbvdhHA7O89AhkuBYkC3L6y36LXc2CutxwzJHDEI8owDrFtI12l92WrZmP0Y5?gv=true
  twitter: https://twitter.com/Charizone_UK
  linkedin: https://www.linkedin.com/company/charizone/
