site_name: Charizone
site_url: !ENV DEPLOY_PRIME_URL
theme:
  name: null
  custom_dir: cz_theme
plugins:
  cz_blog:
    footernav:
      - Read our FAQs: "articles/2022-06-01-faqs.md"
      - About: "about.md"
      - Our Methodology: "our-methodology.md"
    articles_folder: articles
    privacy: "privacy.md"
    terms: "terms-and-conditions.md"
  gen-files:
    scripts:
      - add_charities.py
nav:
  - About: "about.md"
  - Product: "product.md"
  - Resources: "articles.md"
  - Contact: "contact.md"
watch:
  - cz_theme
  - cz_blog
  - add_charities.py
extra:
  twitter: https://twitter.com/Charizone_UK
  linkedin: https://www.linkedin.com/company/charizone/
