site_name: Charizone
site_url: !ENV DEPLOY_PRIME_URL
site_description: We help funders and donors to scale their impact, and give with even more confidence.
site_author: Charizone
theme:
  name: null
  custom_dir: cz_theme
  locale: en
plugins:
  cz_blog:
    footernav:
      - About: "about.md"
      - Resources: "articles.md"
      - Contact: "contact.md"
    articles_folder: articles
    privacy: "privacy.md"
    terms: "terms-and-conditions.md"
  rss:
    enabled: true
    match_path: "articles/.*"
    pretty_print: false
    image: static/images/CharizoneIcon.svg
    date_from_meta:
      as_creation: "date"
      as_update: "date"
      datetime_format: "%Y-%m-%d"
      default_time: "08:20"
    feeds_filenames:
      json_created: feed.json
      json_updated: feed-updated.json
      rss_created: rss.xml
      rss_updated: rss-updated.xml
  markdownextradata: {}
  redirects:
    redirect_maps:
      "articles/2026-09-10- Fore impact report.md": "articles/2026-09-10-fore-impact-report.md"
      "articles/2026-04-09-LBF impact report.md": "articles/2026-04-09-lbf-impact-report.md"
nav:
  - About: "about.md"
  - Our approach: "approach.md"
  - Resources: "articles.md"
  - Contact: "contact.md"
watch:
  - cz_theme
  - cz_blog
extra:
  appointment_booker: https://calendar.google.com/calendar/appointments/schedules/AcZssZ1Rif_CiZSLSMJzbvdhHA7O89AhkuBYkC3L6y36LXc2CutxwzJHDEI8owDrFtI12l92WrZmP0Y5?gv=true
  twitter: https://twitter.com/Charizone_UK
  linkedin: https://www.linkedin.com/company/charizone/
